[build]
target = "x86_64-sosaltix2.json"

[unstable]
json-target-spec = true
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
panic-abort-tests = true

[target.'cfg(target_os = "none")']
runner = "bootimage runner"