[target.x86_64-unknown-none]
rustflags = ["-C", "link-arg=-Tlinker.ld"]

[unstable]
json-target-spec = true
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
panic-abort-tests = true
bindeps = true

[target.'cfg(target_os = "none")']
runner = "bootloader"

#[target.x86_64-unknown-none]
#runner = "qemu-system-x86_64"
